### ISSUE TITLE
git-version-macro name on crates.io

### ISSUE THREAD

**Issue by de-vri-es** [droundy/git-version-macro#1]
Hey, since we now merged the proc macro in https://github.com/m-ou-se/rust-git-version/pull/7, could we use the name `git-version-macro` on crates.io for the macro crate?

If you agree, can you transfer ownership to me or @m-ou-se? We'll take care of the rest then.

**Comment by droundy** [comment]
Yes indeed.  I believe I've just done so.

Let me know if the transfer works!

**Comment by de-vri-es** [comment]
It worked. Thanks!
